from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import browser_cookie3

from dj_dl.config import load_config

APPLE_MUSIC_URL = "https://music.apple.com"
COOKIE_NAME = "media-user-token"


def _try_read_browser_cookies() -> str | None:
    browsers: list[Callable] = [
        browser_cookie3.chrome,
        browser_cookie3.firefox,
        browser_cookie3.edge,
        browser_cookie3.safari,
    ]

    for browser_fn in browsers:
        try:
            cj = browser_fn()
            for cookie in cj:
                if cookie.name == COOKIE_NAME and "apple.com" in cookie.domain and cookie.value:
                    return cookie.value
        except Exception:
            continue

    return None


def _extract_with_playwright() -> str | None:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return None

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        page.goto(APPLE_MUSIC_URL)
        page.wait_for_load_state("networkidle")

        input(
            "\nBrowser opened to music.apple.com. "
            "Please log in to Apple Music if needed, "
            "then press Enter here to save auth..."
        )

        cookies = context.cookies()
        browser.close()

        for cookie in cookies:
            if (
                cookie["name"] == COOKIE_NAME
                and "apple.com" in cookie["domain"]
                and cookie["value"]
            ):
                return cookie["value"]

    return None


def _has_existing_auth() -> bool:
    config = load_config()
    if not config.apple_music.cookies_path:
        return False
    return Path(config.apple_music.cookies_path).exists()


def authenticate_apple_music_interactive() -> tuple[bool, str]:
    if _has_existing_auth():
        print("Apple Music auth already exists.")
        choice = input("Keep current token or set new one? (k/s): ").strip().lower()
        if choice == "k":
            return True, "Kept existing Apple Music auth."
        if choice != "s":
            return False, "Invalid choice. Run again and type 'k' to keep or 's' to set new."

    print("=" * 60)
    print("  Apple Music Authentication")
    print("=" * 60)
    print()
    print("To download from Apple Music, you need to provide your")
    print("media-user-token cookie.")
    print()
    print("Steps:")
    print("  1. Open Chrome and go to: https://music.apple.com")
    print("  2. Make sure you are logged in to your Apple Music account")
    print("  3. Press F12 (or right-click → Inspect)")
    print("  4. Go to: Application → Cookies → https://music.apple.com")
    print("  5. Find the row named: media-user-token")
    print("  6. Right-click on the value → Copy value")
    print()
    print("=" * 60)
    print()

    token = input("Paste your media-user-token here: ").strip()

    if not token:
        return False, "No token provided."

    config = load_config()
    config.apple_music.cookies_path = _save_cookies(token)
    config.save()

    print()
    print("=" * 60)
    print("  Apple Music auth saved successfully!")
    print("=" * 60)
    print()
    print("You can now download Apple Music tracks with:")
    print("  djdl https://music.apple.com/...")
    print()

    return True, "Apple Music auth saved."


def _save_cookies(token: str) -> str:
    cookie_path = Path.home() / ".config" / "dj-dl" / "apple_music_cookies.txt"
    cookie_path.parent.mkdir(parents=True, exist_ok=True)

    netscape_cookie = (
        "# Netscape HTTP Cookie File\n"
        "# This file was generated by dj-dl\n"
        ".music.apple.com\tTRUE\t/\tFALSE\t1750000000\t"
        f"media-user-token\t{token}\n"
    )

    cookie_path.write_text(netscape_cookie)
    return str(cookie_path)
